# Generated by Django 4.2.9 on 2024-01-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_university_id_user_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
