# Generated by Django 4.2.8 on 2024-01-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('university_id', models.AutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(default='', max_length=255)),
                ('api_url', models.CharField(default='', max_length=255)),
                ('term_format', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('canvas_id', models.IntegerField(null=True)),
                ('canvas_secret', models.CharField(max_length=255, null=True)),
                ('university_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=255)),
                ('setting', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.setting')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usersetting',
            constraint=models.UniqueConstraint(fields=('user', 'setting'), name='user_setting'),
        ),
    ]
