# Generated by Django 4.2.8 on 2024-01-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='university_id',
            new_name='university',
        ),
    ]
